---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# ckutils

<!-- badges: start -->
<!-- badges: end -->

The goal of ckutils is to provide some utilities for close-kin study design and implementation.

## Installation

You can install the development version of ckutils from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("rasutt/ckutils")
```

## Example

This is a basic example which shows you how to simulate a wildlife population and a sampling-survey study of it:

```{r example}
# Load close-kin utilities package
library(ckutils)

# Plot the expected population size for a particular scenario
plot_exp_pop(
  sim_years = 1:20, exp_N_t = 20*1.05^(1:20), base_yr = 1, exp_N_base = 20,
  srvy_yrs = c(18, 20)
)
```
```{r}
# Find expected numbers of kin-pairs in population
find_exp_ns_kps(
    exp.N.t = 20*1.05^(1:20), s.yr.inds = 1:2, phi = 0.9, rho = 0.15, 
    lambda = 1.05, alpha = 5, srvy.yrs = c(18, 20), k = 2
)
```
```{r}
# Set random seed for testing
set.seed(1)

# Simulate one population and study
pop_study = sim_pop_study(
  phi = 0.9, lambda = 1.05, N.init = 20, hist.len = 20, srvy.yrs = 20, k = 1,
  f.year = 20, p = 0.5, L = 10, imaf = 0.5, clvng.p = 0, tmp.emgn = 0,
  alpha = 5, clvng.ints = F
)

# Look at it
head(pop_study)
```
```{r}
names(attributes(pop_study))
```
