---
title: "Kinship PLODs"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{kinship-PLODs}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(ckutils)
```

## Finding half-sibling versus unrelated pair PLODs

```{r}
# Load a single simulated study and associated parameters
load("../data/single_study.RData")

# Load possible genopair probabilities
load(file = "../data/possible_genopair_probabilities.RData")

# Load observed genopair probabilities
load(file = "../data/observed_genopair_probabilities.RData")
dfr2(head(oglps))

# Half-sibling versus unrelated pair PLODs
hsp_up_plods = find_hsp_up_plods(oglps, L)

# Find expected values of half-sibling versus unrelated pair PLODs given various
# kinships
exp_plods = find_exp_plods(pgps, L)

# Plot half-sibling versus unrelated pair PLODs on log-scale
plot_plods(hsp_up_plods, exp_plods, show_legend = F)
```

