---
title: "Simulating populations and studies"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Simulating populations and studies}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(ckutils)
```

This is a basic example which shows you how to simulate a wildlife population and a sampling-survey study of it:

```{r example}
# Load close-kin utilities package
library(ckutils)

# Population size in reference year
ref_yr = 2010
exp_N_ref = 1500

# Population growth rate
lambda = 1.05

# Survey years
srvy_yrs = c(2010, 2015, 2020)

# Simulation length
sim_len = 50

# Simulation years
fnl_yr = tail(srvy_yrs, 1)
init_yr = fnl_yr - sim_len + 1
sim_yrs = init_yr:fnl_yr

# Expected population size over simulation years
exp_N_init = exp_N_ref * lambda^(init_yr - ref_yr)
exp_N_t = exp_N_init * lambda^(0:(sim_len - 1))

# Plot expected population size over simulation years
plot_exp_pop(sim_yrs, exp_N_t, ref_yr, exp_N_ref, srvy_yrs)
```
```{r}
# Find expected numbers of kin-pairs in population
find_exp_ns_kps(
    exp.N.t = 20*1.05^(1:20), s.yr.inds = 1:2, phi = 0.9, rho = 0.15, 
    lambda = 1.05, alpha = 5, srvy.yrs = c(18, 20), k = 2
)
```
```{r}
# Set random seed for testing
set.seed(1)

# Simulate one population and study
pop_study = sim_pop_study(
  phi = 0.9, lambda = 1.05, N.init = 20, hist.len = 20, srvy.yrs = 20, k = 1,
  f.year = 20, p = 0.5, L = 10, imaf = 0.5, clvng.p = 0, tmp.emgn = 0,
  alpha = 5, clvng.ints = F
)

# Look at it
head(pop_study)
```
```{r}
names(attributes(pop_study))
```
